dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank


jobs:
  include:
    - stage: build and publish
      language: java
      jdk: openjdk11
      install: skip
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Raghunandan8142066677"
        - git config --local user.email "raghu053010@gmail.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: 469e7534843e2322e722139d31b77506eb873286
        file: "build/libs/pal-tracker.jar"
        skip_cleanup: true
    - stage: deploy to cf
      language: bash
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/$GITHUB_USERNAME/pal-tracker/releases/download/$RELEASE_TAG/pal-tracker.jar
      before_deploy:
        - echo "Deploying $RELEASE_TAG to Cloud Foundry"
      deploy:
        provider: cloudfoundry
        api: api.run.pivotal.io
        username: raghunandan.tumkunta@wipro.com
        password: Raghu@123
        organization: RaghunandanOrg
        space: development
